export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGIN_TRUE = 'USER_LOGIN_TRUE';
export const USER_AUTH_START = 'USER_AUTH_START';
export const USER_CHECKTIMEOUT = 'USER_CHECKTIMEOUT';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_USERSIGNUP = 'AUTH_USERSIGNUP';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';